CREATE TABLE dates (
    id TEXT PRIMARY KEY UNIQUE NOT NULL,
    users_id TEXT REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE NOT NULL,
    users_id1 TEXT REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE NOT NULL,
    date TIMESTAMP NOT NULL,
    places_id TEXT REFERENCES places(id) ON DELETE RESTRICT ON UPDATE CASCADE NOT NULL
);